export enum ERateElementType {
  EnergyTimeOfUse = 'EnergyTimeOfUse',
  BlockedTiersInDays = 'BlockedTiersInDays',
  BlockedTiersInMonths = 'BlockedTiersInMonths',
  FixedPerDay = 'FixedPerDay',
  FixedPerMonth = 'FixedPerMonth',
  MonthlyDemand = 'MonthlyDemand',
  AnnualDemand = 'AnnualDemand',
  MonthlyEnergy = 'MonthlyEnergy',
  SurchargeAsPercent = 'SurchargeAsPercent',
  HourlyEnergy = 'HourlyEnergy',
  DemandTiersInMonths = 'DemandTiersInMonths',
  DemandTimeOfUse = 'DemandTimeOfUse',
  DemandPerDay = 'DemandPerDay',
}

export const RATE_ELEMENT_SORT_ORDER = {
  [ERateElementType.FixedPerMonth]: 1,
  [ERateElementType.FixedPerDay]: 2,
  [ERateElementType.AnnualDemand]: 3,
  [ERateElementType.MonthlyDemand]: 4,
  [ERateElementType.DemandTiersInMonths]: 5,
  [ERateElementType.DemandTimeOfUse]: 6,
  [ERateElementType.DemandPerDay]: 7,
  [ERateElementType.MonthlyEnergy]: 8,
  [ERateElementType.HourlyEnergy]: 9,
  [ERateElementType.EnergyTimeOfUse]: 10,
  [ERateElementType.BlockedTiersInDays]: 100,
  [ERateElementType.BlockedTiersInMonths]: 100,
  [ERateElementType.SurchargeAsPercent]: 100,
};
